gateways:
  duckdb:
    connection:
      # For more information on configuring the connection to your execution engine, visit:
      # https://sqlmesh.readthedocs.io/en/stable/reference/configuration/#connection
      # https://sqlmesh.readthedocs.io/en/stable/integrations/engines/duckdb/#connection-options
      type: duckdb
      catalogs:
        persistent: '../data/local_data_mart.duckdb'
        my_lakehouse:
          type: ducklake
          path: '../data/catalog.ducklake.sqlite3'
          # data_path: '/Users/m-nakamura/Documents/2026-01_ducklake_example/data/storage'
      extensions:
        - ducklake
    state_connection:
      type: duckdb
      database: '../data/sqlmesh_state.duckdb'

default_gateway: duckdb

# --- Model Defaults ---
# https://sqlmesh.readthedocs.io/en/stable/reference/model_configuration/#model-defaults

model_defaults:
  dialect: duckdb
  start: 1995-01-01 # Start date for backfill history
  cron: '@daily'    # Run models daily at 12am UTC (can override per model)

# --- Linting Rules ---
# Enforce standards for your team
# https://sqlmesh.readthedocs.io/en/stable/guides/linter/

linter:
  enabled: true
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion
    - noambiguousprojections
